-- MySQL Script generated by MySQL Workbench
-- Sat Oct  6 13:37:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
	`id` INT NOT NULL auto_increment,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `tipo` ENUM('Vestibular', 'Transferencia') NULL,
  `dataNascimento` date NULL,
  PRIMARY KEY (`id`),
  unique(`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
		`id` INT NOT NULL auto_increment,
  `codigo` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `bloco` CHAR NULL,
  PRIMARY KEY (`id`),
  unique(`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `id` int not null auto_increment,
  `codigo` VARCHAR(10) NOT NULL,
  `nomeCurso` VARCHAR(100) NULL,
  `numeroCreditoConclusao` INT NULL,
  `idDepartamento` int NOT NULL,
  PRIMARY KEY (`id`),
  unique(`codigo`),
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `id` int not null auto_increment,
  `numeroMatricula` VARCHAR(10) NOT NULL,
  `idCurso` int NOT NULL,
  `tipo` ENUM('Ativo', 'Inativo') NULL,
  `dataInicio` date NULL,
  `idAluno` int NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Curso` (`id`),
    FOREIGN KEY (`idAluno`)
    REFERENCES `mydb`.`Aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_Endereco` (
  `id` int not null auto_increment,
  `cpfAluno` VARCHAR(11) not null,
  `rua` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  primary key(id),
    FOREIGN KEY (`cpfAluno`)
    REFERENCES `mydb`.`Aluno` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `id` int not null auto_increment,
  `matriculaProfessor` VARCHAR(10) NOT NULL,
  `CFE` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `idDepartamento` int NOT NULL,
  PRIMARY KEY (`id`),
  unique(`matriculaProfessor`),
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
	`id` int not null auto_increment,
  `codigo` VARCHAR(10) NOT NULL,
  `numeroTotalHoras` INT NULL,
  `idDepartamento` int NOT NULL,
  `cargaHoraria` INT NULL,
  `credito` INT NULL,
  `tipo` ENUM('Ativo', 'Inativo') NULL,
  `nomeDisciplina` VARCHAR(45) NULL,
  `idProfessor` int NOT NULL,
  PRIMARY KEY (`id`),
  unique(`codigo`),
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idProfessor`)
    REFERENCES `mydb`.`Professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `id` int not null auto_increment,
  `idMatricula` int NOT NULL,
  `idDisciplina` int NOT NULL,
  `notaFinal` FLOAT NULL,
  `dataCursada` date NULL,
  PRIMARY KEY(id),
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idMatricula`)
    REFERENCES `mydb`.`Matricula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursando` (
  `id` int not null auto_increment,
  `idMatricula` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  `primeiroGQ` DOUBLE NULL,
  `segundoGQ` double NULL,
  primary key(id),
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idMatricula`)
    REFERENCES `mydb`.`Matricula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composto_Obrigatoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Composto_Obrigatoria` (
  `id` int not null auto_increment,
  `idDisciplina` int NOT NULL,
  `idCurso` int NOT NULL,
  primary key(id),
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Optativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Optativa` (
  `id` int not null auto_increment,
  `idDisciplina` int NOT NULL,
  `idCurso` int NOT NULL,
  primary key(id),
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



